version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp index.html $READTHEDOCS_OUTPUT/html/index.html
    - mkdir -p $READTHEDOCS_OUTPUT/html/security-in-age-of-ai
    - cp -r security-in-age-of-ai/. $READTHEDOCS_OUTPUT/html/security-in-age-of-ai/
